Ext.define 'BRK-Webapp.model.app'
  extend: 'Ext.data.Model'
  fields: [
      'api_url'
      'description'
      'portal_type'
      'tags'
      'modified'
      'url'
      'title'
      'type'
      'id'
      'created'
      'effective'
    ]