Ext.define 'BRK-Webapp.model.appmod'
  extend: 'Ext.data.Model'
  fields: [
  	  'effective'
  	  'modified'
      'text'
      'text_plain'
      'thumbnail'
      'description'
      'image1_text'
      'image2_text'
      'image3_text'
      'image1'
      'image2'
      'image3'
      'title'
      'start_date'
      'end_date'
      'location'
      'url'
    ]